#include <iostream>
#include "..\Galt-Engine\Window.h"
#include "..\Galt-Engine\Camera.h"
#include "..\Galt-Engine\Timer.h"
#include "..\Galt-Engine\KeyInput.h"
#include "..\Galt-Engine\Particle.h"
#include "..\Galt-Engine\ParticleEmitter.h"
#include "..\Galt-Engine\Input.h"
#include <ctime>